### ISSUE TITLE
TODO

### ISSUE THREAD

**Issue by virtualdreams** [virtualdreams/notes-core#1]
- [ ] ~~File upload~~
- [x] Insert tabulator (4)
- [ ] Search just in notebook or tag
- [x] Save and continue
- [ ] History
- [x] Save counter
- [ ] ~~Tasks~~
- [ ] ~~Favorites / Quick access~~
- [ ] Share notes
- [ ] Publish
- [ ] User management
- [ ] Sort notes
